#include "ChatAgent.h"
#include <juce_core/juce_core.h>

using json = nlohmann::json;

namespace aria {

ChatAgent::ChatAgent(LLMRuntime& llm) : llm_(llm) {}

std::string ChatAgent::buildSystemPrompt(const SongDocument& doc) const
{
    auto& meta = doc.metadata();

    // Build instrument list
    std::string instruments;
    if (doc.tracks().empty()) {
        instruments = "none yet";
    } else {
        for (size_t i = 0; i < doc.tracks().size(); ++i) {
            if (i > 0) instruments += ", ";
            instruments += doc.tracks()[i].instrument.toStdString();
        }
    }

    // Load CHAT.md system prompt from embedded binary data
    // (BinaryData is generated by juce_add_binary_data in CMakeLists.txt)
    // For now, inline a condensed version:
    std::string systemPrompt = R"(You are IRA, a friendly AI music assistant inside the ARIA DAW.
Your job is to understand what the user wants and produce a JSON intent object.

Rules:
- Reply ONLY with valid JSON. No markdown, no explanation, no preamble.
- If the user wants to generate music, set type to "generate" and fill all fields.
- If the user is chatting, set type to "chat" and put your reply in "reply".
- If uncertain about bpm/key/bars — make a tasteful guess that fits the vibe.

Output schema:
{"type":"generate"|"chat"|"feedback"|"regenerate","reply":"<friendly message>","vibe":"<mood>","genre":"<genre>","bpm":<int>,"key":"<note> <mode>","bars":<int>,"instruments":["drums","bass",...]}
)";

    systemPrompt += "\nCURRENT PROJECT:\n";
    systemPrompt += "  BPM: " + std::to_string(static_cast<int>(meta.bpm)) + "\n";
    systemPrompt += "  Key: " + meta.key.toStdString() + "\n";
    systemPrompt += "  Bars: " + std::to_string(meta.bars) + "\n";
    systemPrompt += "  Tracks: " + instruments + "\n";

    return systemPrompt;
}

json ChatAgent::process(
    const std::string&                    userMessage,
    const SongDocument&                   currentDoc,
    std::function<void(std::string_view)> tokenCallback)
{
    auto systemPrompt = buildSystemPrompt(currentDoc);

    std::string raw;
    if (tokenCallback) {
        // Stream tokens to UI while generating
        llm_.inferStream(systemPrompt, userMessage,
            [&](std::string_view token) {
                raw += token;
                tokenCallback(token);
            });
    } else {
        raw = llm_.inferJSON(systemPrompt, userMessage, LLMRuntime::intentGrammar());
    }

    // Parse JSON
    try {
        return json::parse(raw);
    } catch (...) {
        juce::Logger::writeToLog("[ChatAgent] Failed to parse JSON: " + juce::String(raw.c_str()));
        return {{"type", "chat"}, {"reply", "Sorry, I couldn't understand that. Please try again."}};
    }
}

} // namespace aria
